https://pypi.org/project/pyDOE2/

In [2]:
!pip install pyDOE3

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 kB 3.2 MB/s eta 0:00:00


In [3]:
from pyDOE3 import *

# Central Composite Design (CCD)

# face options

* circumscribed = ccc
* inscribed = cci
* faced = ccf

# alpha options

* orthogonal = 'o'
* rotatable = 'r'

In [16]:
ccdesign(4, center=(0,0), alpha='o', face='ccc')

array([[-1., -1., -1., -1.],
       [-1., -1., -1.,  1.],
       [-1., -1.,  1., -1.],
       [-1., -1.,  1.,  1.],
       [-1.,  1., -1., -1.],
       [-1.,  1., -1.,  1.],
       [-1.,  1.,  1., -1.],
       [-1.,  1.,  1.,  1.],
       [ 1., -1., -1., -1.],
       [ 1., -1., -1.,  1.],
       [ 1., -1.,  1., -1.],
       [ 1., -1.,  1.,  1.],
       [ 1.,  1., -1., -1.],
       [ 1.,  1., -1.,  1.],
       [ 1.,  1.,  1., -1.],
       [ 1.,  1.,  1.,  1.],
       [-2.,  0.,  0.,  0.],
       [ 2.,  0.,  0.,  0.],
       [ 0., -2.,  0.,  0.],
       [ 0.,  2.,  0.,  0.],
       [ 0.,  0., -2.,  0.],
       [ 0.,  0.,  2.,  0.],
       [ 0.,  0.,  0., -2.],
       [ 0.,  0.,  0.,  2.]])

# D-optimal

In [ ]:
import numpy as np
from itertools import product, combinations, permutations #시간 효율성 매우 낮음
import math

In [ ]:
num_factors = 3  #설계 인자의 개수
num_samples = 15  #선택할 실험 점의 개수
levels = [-1, 0, 1]  #각 요인의 수준 설정

In [ ]:
def generate_design_space(num_factors, levels):
    design_space = np.array(list(product(levels, repeat=num_factors)))
    return design_space

In [ ]:
def calculate_d_optimal_score(selected_samples):
    X = np.hstack((np.ones((selected_samples.shape[0], 1)), selected_samples))
    XT_X = np.dot(X.T, X)
    det_XT_X = np.linalg.det(XT_X)
    return -det_XT_X

In [ ]:
design_space = generate_design_space(num_factors, levels)

In [ ]:
def find_d_optimal_design(design_space, num_samples):
    best_score = np.inf
    best_design = None

    all_combinations = list(combinations(design_space, num_samples))

    num_combinations_to_check = math.ceil(len(all_combinations) / num_factors)
    selected_combinations = all_combinations[:num_combinations_to_check]

    for selected_samples in selected_combinations:
        selected_samples = np.array(selected_samples)
        score = calculate_d_optimal_score(selected_samples)

        if score < best_score:
            best_score = score
            best_design = selected_samples

    return best_design, -best_score

In [ ]:
# 설계 공간 생성
design_space = generate_design_space(num_factors, levels)

# D-최적 설계 찾기
best_design, best_score = find_d_optimal_design(design_space, num_samples)

print("Best D-optimal design:")
print(best_design)
print("Best D-optimal score:", best_score)

Best D-optimal design:
[[-1 -1 -1]
 [-1 -1  0]
 [-1 -1  1]
 [-1  0 -1]
 [-1  0  1]
 [-1  1 -1]
 [-1  1  1]
 [ 0  1 -1]
 [ 0  1  1]
 [ 1 -1 -1]
 [ 1 -1  0]
 [ 1 -1  1]
 [ 1  0 -1]
 [ 1  1 -1]
 [ 1  1  1]]
Best D-optimal score: 29903.999999999993


## LHS

In [8]:
lhs(2, samples=15)